export const styleActionTypes = {
    TOGGLE_DRAWER_SIDEBAR:'TOGGLE_DRAWER_SIDEBAR',
    TOGGLE_DRAWER_MAINNAV: 'TOGGLE_DRAWER_MAINNAV'
}

export const productsActionTypes = {
    SET_ALL_PRODUCTS:'SET_ALL_PRODUCTS',
    SET_OPEN_MODAL: 'SET_OPEN_MODAL',
    SET_SEARCH_QUERY: 'SET_SEARCH_QUERY',
    SET_PRICE_RANGE: 'SET_PRICE_RANGE',
    SET_MIN_MAX_PRICE: 'SET_MIN_MAX_PRICE',
    SET_CATEGORY: 'SET_CATEGORY',
    SET_SORT_TYPE: 'SET_SORT_TYPE'
}